name: Build PanIndex

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup FreeBSD base
        run: |
          wget -q https://download.freebsd.org/releases/amd64/14.3-RELEASE/base.txz
          sudo mkdir /opt/freebsd && sudo tar -xf ./base.txz -C /opt/freebsd

      - name: Build PanIndex
        run: |
          export LATEST_APP=$(wget -qO- https://api.github.com/repos/px-org/PanIndex/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          git clone -b $LATEST_APP https://github.com/px-org/PanIndex
          cd PanIndex
          bash ../build.sh

      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(wget -qO- https://api.github.com/repos/px-org/PanIndex/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PanIndex/PanIndex
          token: ${{ github.token }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
